general.import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "IosevkaTermSlab Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaTermSlab Nerd Font"
style = "Bold Oblique"

[font.italic]
family = "IosevkaTermSlab Nerd Font"
style = "Oblique"

[font.normal]
family = "IosevkaTermSlab Nerd Font"
style = "Regular"
