#!/bin/sh

HISTSIZE=1000000
SAVEHIST=1000000
HISTFILE="$XDG_DATA_HOME"/zsh/history
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH="$HOME/.local/bin":$PATH
export STARSHIP_CONFIG="$XDG_CONFIG_HOME"/starship/config.toml
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

