#!/bin/zsh

HISTSIZE=1000000
SAVEHIST=1000000
HISTFILE="$XDG_DATA_HOME"/zsh/history
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH="$HOME/.local/bin":$PATH
export STARSHIP_CONFIG="$XDG_CONFIG_HOME"/starship/config.toml
export NVM_DIR="$HOME/.config/nvm"
export GCM_CREDENTIAL_STORE="gpg"
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/caio/.mambaforge/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/caio/.mambaforge/etc/profile.d/conda.sh" ]; then
        . "/home/caio/.mambaforge/etc/profile.d/conda.sh"
    else
        export PATH="/home/caio/.mambaforge/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

