#!/bin/bash

HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PYENV_ROOT=$HOME/.pyenv
export NVM_DIR="$HOME/.config/nvm"
export PATH=$HOME/.cargo/bin:$PATH
export PATH="$HOME/.local/bin:$PATH"
export PATH="$PYENV_ROOT/bin:$PATH"
export STARSHIP_CONFIG="$XDG_CONFIG_HOME"/starship/config.toml
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
# eval "`pip completion --zsh`"
