#!/bin/zsh

# Some useful options (man zshoptions)
unsetopt BEEP # beeping is annoying
setopt autocd extendedglob nomatch menucomplete
setopt interactive_comments
setopt hist_ignore_all_dups
set show-mode-in-prompt on
stty stop undef	# Disable ctrl-s to freeze terminal.
zle_highlight=('paste:none')

source $XDG_DATA_HOME/catppuccin/catppuccin_mocha-zsh-syntax-highlighting.zsh
source "$HOME/.cargo/env"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
eval "$(sheldon source)"

# # Edit line in vim with ctrl-e:
# autoload edit-command-line; zle -N edit-command-line
# # bindkey '^e' edit-command-line
autoload -Uz colors && colors
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

bindkey -s '^o' 'nnn^M'
bindkey -s '^f' 'zi^M'
bindkey -s '^s' 'ncdu^M'
bindkey -s '^z' 'zi^M'
bindkey '^[[P' delete-char
bindkey "^p" up-line-or-beginning-search # Up
bindkey "^n" down-line-or-beginning-search # Down
bindkey "^k" up-line-or-beginning-search # Up
bindkey "^j" down-line-or-beginning-search # Down
bindkey -r "^u"
bindkey -r "^d"

zstyle ':completion:*' menu select
# zstyle ':completion::complete:lsof:*' menu yes select
zmodload zsh/complist

source "$ZDOTDIR/zsh-exports"
source "$ZDOTDIR/zsh-vim-mode"
source "$ZDOTDIR/zsh-aliases"

autoload -Uz compinit
_comp_options+=(globdots) # Include hidden files.
compinit

if command -v tmux &> /dev/null && [ -n "$PS1" ] && [ -z "$TMUX" ]; then
    exec tmux new-session -A -s main
fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$HOME/.miniforge3/bin/conda" 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/.miniforge3/etc/profile.d/conda.sh" ]; then
        . "$HOME/.miniforge3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/.miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "$HOME/.miniforge3/etc/profile.d/mamba.sh" ]; then
    . "$HOME/.miniforge3/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<
