local opts = { noremap = true, silent = true }
vim.keymap.set("n", "<leader>n", "<cmd>NnnPicker %:p:h<CR>", opts)
vim.keymap.set("n", "<leader>F", "<cmd>Format<CR>", opts)
require("luasnip.loaders.from_vscode").lazy_load()
vim.keymap.set("n", "gd",  "<cmd>Telescope lsp_definitions<CR>", {})
vim.keymap.set("n", "gr", "<cmd>Telescope lsp_references<CR>", {})
vim.keymap.set("n", "gi", "<cmd>Telescope lsp_incoming_calls<CR>", {})
vim.keymap.set("n", "go", "<cmd>Telescope lsp_outgoing_calls<CR>", {})
vim.keymap.set('n', '<leader>p', "<cmd>Telescope find_files<CR>", {})
vim.keymap.set('n', '<leader>fg', "<cmd>Telescope live_grep<CR>", {})
vim.keymap.set('n', '<leader>fb', "<cmd>Telescope buffers<CR>", {})
vim.keymap.set('n', '<leader>fo', "<cmd>Telescope oldfiles<CR>", {})
vim.keymap.set('n', '<leader>fC', "<cmd>Telescope commands<CR>", {})
vim.keymap.set('n', '<leader>fc', "<cmd>Telescope command_history<CR>", {})
vim.keymap.set('n', '<leader>fh', "<cmd>Telescope help_tags<CR>", {})
vim.keymap.set('n', '<leader>fT', "<cmd>Telescope diagnostics<CR>", {})
vim.keymap.set('n', '<leader>fT', "<cmd>Telescope diagnostics buffnr 0<CR>", {})
vim.keymap.set("n", "<leader>fu", "<cmd>Telescope undo<cr>")
