onlyOneBackUp: 1
defaultIndent: "    "
removeTrailingWhitespace: 1
lookForAlignDelims:
  align: 0
  tabular:
    alignRowsWithoutMaxDelims: 0
modifyLineBreaks:
  textWrapOptions:
    columns: 100
    oneSentencePerLine:
        manipulateSentences: 1
        sentencesEndWith:
            basicFullStop: 0
            betterFullStop: 0
            questionMark: 0
            other: '(?:\.\)(?!\h*[a-z]))|(?:\?\})|(?:\.\})|(?:(?<!(?:(?:e\.g)|(?:i\.e)|(?:etc))))\.(?!(?:[a-z]|[A-Z]|\-|~|\,|[0-9]))'
