local keymap = vim.keymap
local diagnostic = vim.diagnostic
local opts = { noremap = true, silent = true }

keymap.set("n", "<leader>e", diagnostic.open_float)
keymap.set("n", "[d", diagnostic.goto_prev)
keymap.set("n", "]d", diagnostic.goto_next)
keymap.set("n", "<leader>q", diagnostic.setloclist)
keymap.set("n", "<leader>/", [[:nohl<CR>]], opts)
keymap.set({ "n", "v", "o", "i" }, "<up>", "<nop>", opts)
keymap.set({ "n", "v", "o", "i" }, "<down>", "<nop>", opts)
keymap.set({ "n", "v", "o", "i" }, "<left>", "<nop>", opts)
keymap.set({ "n", "v", "o", "i" }, "<right>", "<nop>", opts)
keymap.set("n", "<leader>n", "<cmd>NnnPicker %:p:h<CR>", opts)
keymap.set("n", "<leader>F", "<cmd>Format<CR>", opts)
keymap.set("n", "gd", "<cmd>Telescope lsp_definitions<CR>", {})
keymap.set("n", "gr", "<cmd>Telescope lsp_references<CR>", {})
keymap.set("n", "gi", "<cmd>Telescope lsp_incoming_calls<CR>", {})
keymap.set("n", "go", "<cmd>Telescope lsp_outgoing_calls<CR>", {})
keymap.set("n", "<leader>p", "<cmd>Telescope find_files<CR>", {})
keymap.set("n", "<leader>fg", "<cmd>Telescope live_grep<CR>", {})
keymap.set("n", "<leader>fb", "<cmd>Telescope buffers<CR>", {})
keymap.set("n", "<leader>fo", "<cmd>Telescope oldfiles<CR>", {})
keymap.set("n", "<leader>fC", "<cmd>Telescope commands<CR>", {})
keymap.set("n", "<leader>fc", "<cmd>Telescope command_history<CR>", {})
keymap.set("n", "<leader>fh", "<cmd>Telescope help_tags<CR>", {})
keymap.set("n", "<leader>fT", "<cmd>Telescope diagnostics<CR>", {})
keymap.set("n", "<leader>fT", "<cmd>Telescope diagnostics buffnr 0<CR>", {})
keymap.set("n", "<leader>fu", "<cmd>Telescope undo<cr>")
keymap.set("n", "<leader>l", '<cmd>:lua require("nabla").popup()<cr>')
